#
language: python

os:
  - linux

env:
    matrix:
        - ENV_NAME="test-environment"
          PYTHON_VERSION=3.7
          PACKAGES="ipython>=7.0.0 numpy scipy matplotlib pandas jupyter cython proj4=5.2.0"

branches:
  only:
    - master

jobs:
  include:
    - dist: xenial

# Install dependencies
install:
  # Install miniconda
  # -----------------
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
 

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes
  - conda config --add channels conda-forge

  # Customise the testing environment
  # ---------------------------------
  - conda create -n $ENV_NAME python=$PYTHON_VERSION $PACKAGES
  - source activate $ENV_NAME 
  
  # Install packages
  # ----------------
  - pip install -r requirements.travis.txt
  - pip install --upgrade pip
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-xdist
  - pip install codacy-coverage

# command to run tests
script:
  - py.test ./autotest/test_01_basic.py -n 3
  - py.test ./autotest/test_02_on_topic.py -n 3
after_success:
  - python-codacy-coverage -r coverage.xml